// プリセット統合テスト Part 2/8
// 自動生成：generators/generate_split_fixture_tests.rs

use nksf_parser::parse_nksf;
use rstest::rstest;
use std::path::PathBuf;

#[rstest]
#[case("Broken Arrow")]
#[case("Broken Bow")]
#[case("Broken Silver")]
#[case("Bubble Inertia")]
#[case("Budgie Bot")]
#[case("Bump Force")]
#[case("Buried Giant")]
#[case("Burn Da Speaker")]
#[case("Burning Psykoma")]
#[case("Burnt Biscuit")]
#[case("Butterherz")]
#[case("Calm Rocket")]
#[case("Canary")]
#[case("Caps Lock")]
#[case("Castle Ancient")]
#[case("Cathedral")]
#[case("Cathedralium")]
#[case("Celestial Plum")]
#[case("Cellar Blip")]
#[case("Cellar Electric")]
#[case("Cesium")]
#[case("Chalice")]
#[case("Chasing Saws")]
#[case("Chicago Galactic")]
#[case("Chord Xfade")]
#[case("Cielo")]
#[case("Circuit Celesta")]
#[case("Circuit Disrupt")]
#[case("City Jazz")]
#[case("Clap Master")]
#[case("Clapped")]
#[case("Clarity")]
#[case("Claws")]
#[case("Clean Strings")]
#[case("Click Fiend")]
#[case("Cloaked")]
#[case("Clock Face")]
#[case("Cloud Air")]
#[case("Cloud Breaker")]
#[case("Clown Play")]
#[case("Club Tropics")]
#[case("Codeword")]
#[case("Coldest Champion")]
#[case("Comb Experiment")]
#[case("Comb Mallets")]
#[case("Come Together")]
#[case("Constant Value")]
#[case("Corellator")]
#[case("Corn Pop")]
#[case("Counting Comets")]
#[case("Cowboy Sync")]
#[case("Cramp")]
#[case("Crash Party")]
#[case("Crayon")]
#[case("Creak Bark")]
#[case("Creature Space")]
#[case("Crispy Lamb")]
#[case("Croco")]
#[case("Crown Alloy")]
#[case("Cruella")]
#[case("Crush Star")]
#[case("Crystal Cactus")]
#[case("Cute Bar")]
#[case("D Arcelious")]
#[case("Daft")]
#[case("Dark Heart")]
#[case("Data Transmissions")]
#[case("Daybreaker")]
#[case("Dazed Strange")]
#[case("Deception")]
#[case("Deep Blue")]
#[case("Deep Float")]
#[case("Deep Forward")]
#[case("Deep Fried")]
#[case("Deep Growl")]
#[case("Department Box")]
#[case("Desist")]
#[case("Destination Source")]
#[case("Destroyer")]
#[case("Devine Acid")]
#[case("Diesel Dust")]
#[case("Digital Ghost")]
#[case("Dirty Dancer")]
#[case("Dodo Scream")]
#[case("Dolphin")]
#[case("Dopamine Pluck")]
#[case("Down Down")]
#[case("Dream Away")]
#[case("Dreamy Amazonia")]
#[case("Drift Away")]
#[case("Drifter")]
#[case("Dripping Space")]
#[case("Drop Conga")]
#[case("Drop Lazer")]
#[case("Dub Bounce")]
#[case("Dub Salad")]
#[case("Dub Spiral")]
#[case("Dub Stick")]
#[case("Dunkin Bass")]
#[case("Dunkle")]
fn test_parse_preset(#[case] preset_name: &str) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/massive_x_factory_library_tests/fixture")
        .join(format!("{}.nksf", preset_name));

    let nksf = parse_nksf(&path).expect("Failed to parse preset");

    // 全データをYAMLスナップショットとして検証
    insta::assert_yaml_snapshot!(preset_name, nksf);
}
