// プリセット統合テスト Part 5/8
// 自動生成：generators/generate_split_fixture_tests.rs

use nksf_parser::parse_nksf;
use rstest::rstest;
use std::path::PathBuf;

#[rstest]
#[case("Missile Man")]
#[case("Missing Beats")]
#[case("Modern Eight")]
#[case("Modern Funk")]
#[case("Modern Slap")]
#[case("Moldy Organ")]
#[case("Monark King")]
#[case("Monkey Forest")]
#[case("Moon Ark")]
#[case("Moony")]
#[case("Moregan")]
#[case("Morph Suitcase")]
#[case("Morse Chords")]
#[case("Mother Doom")]
#[case("Motor Braam")]
#[case("Mouth Chilly")]
#[case("Moving Monster")]
#[case("Moving On")]
#[case("Mr Snappy")]
#[case("Multi Phasor")]
#[case("Mumble Growl")]
#[case("Music Auto")]
#[case("Muted Axe")]
#[case("Mystery Metal")]
#[case("Mystic Visions")]
#[case("Naked Saw")]
#[case("Naturalistic")]
#[case("Naughties")]
#[case("Naughty Noise")]
#[case("Negative Matter")]
#[case("Neo Soul")]
#[case("Neon Rain")]
#[case("Neu Metal")]
#[case("Night Trails")]
#[case("No Zone")]
#[case("Noise Bells")]
#[case("Noise Pulse")]
#[case("Noise Sub")]
#[case("Not Scary")]
#[case("Now Dystopia")]
#[case("Obsession")]
#[case("Obstacles")]
#[case("Oceanic Storm")]
#[case("Octave Drums")]
#[case("Octave Loop")]
#[case("Odd World")]
#[case("On Fire")]
#[case("One Note")]
#[case("One Patch to Rule Them All")]
#[case("Opaque Saws")]
#[case("Open Close")]
#[case("Optical Tension")]
#[case("Orbit Mist")]
#[case("Orchestra Bubbles")]
#[case("Orchestral Poly")]
#[case("Organ Gator")]
#[case("Organ House")]
#[case("Organic Closer")]
#[case("Organic Log")]
#[case("Outlaw")]
#[case("Over Rainbow")]
#[case("Oxygen Mask")]
#[case("Palm City")]
#[case("Paloma")]
#[case("Pandora")]
#[case("Paradise")]
#[case("Party Bonk")]
#[case("Passive")]
#[case("Pastoral Landscape")]
#[case("Pathways")]
#[case("Pedal Blades")]
#[case("Peters Pan")]
#[case("Phat Phase")]
#[case("Phazer")]
#[case("Piccolino")]
#[case("Pineapple")]
#[case("Ping Latency")]
#[case("Pink Bleep")]
#[case("Pipe Man")]
#[case("Pixel")]
#[case("Plastique")]
#[case("Plate Bender")]
#[case("Playful")]
#[case("Playing The Amp")]
#[case("Plec Snap")]
#[case("Plop Pluck")]
#[case("Pluck Attack")]
#[case("Plucked Up")]
#[case("Plucky")]
#[case("Plush")]
#[case("Poetic Popcorn")]
#[case("Poly Tech")]
#[case("Port Meadow")]
#[case("Primal Leader")]
#[case("Prog Lead")]
#[case("Psy Drips")]
#[case("Pucker")]
#[case("Puffy Mallet")]
#[case("Pulse Rider")]
#[case("Push Kick")]
fn test_parse_preset(#[case] preset_name: &str) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/massive_x_factory_library_tests/fixture")
        .join(format!("{}.nksf", preset_name));

    let nksf = parse_nksf(&path).expect("Failed to parse preset");

    // 全データをYAMLスナップショットとして検証
    insta::assert_yaml_snapshot!(preset_name, nksf);
}
