// プリセット統合テスト Part 6/8
// 自動生成：generators/generate_split_fixture_tests.rs

use nksf_parser::parse_nksf;
use rstest::rstest;
use std::path::PathBuf;

#[rstest]
#[case("Quack")]
#[case("Quantum Foam")]
#[case("Quantum Hopper")]
#[case("Quartet Time")]
#[case("R2T2")]
#[case("Racer Raver")]
#[case("Radioactive")]
#[case("Rampenschutz")]
#[case("Random Orders")]
#[case("Randomitter")]
#[case("Ratios")]
#[case("Rattle Shake")]
#[case("Rattlesnake")]
#[case("Rave Forest")]
#[case("Raving Beast")]
#[case("Reckoning")]
#[case("Reel Keys")]
#[case("Resolute")]
#[case("Retaliation Is A Must")]
#[case("Retro Cruiser")]
#[case("Retro Dub")]
#[case("Retro Hoover")]
#[case("Retro Rise")]
#[case("Retrograde")]
#[case("Ringer")]
#[case("Rip Tear")]
#[case("Rip Teeth")]
#[case("Riser Collection")]
#[case("Rising Star")]
#[case("Rising Sun")]
#[case("Robot Wars")]
#[case("Robotic Ape")]
#[case("Rock Hats")]
#[case("Rock Register")]
#[case("Roller Shake")]
#[case("Rough Rider")]
#[case("Round Trip")]
#[case("Rub Lamp")]
#[case("Rubber")]
#[case("Rubber Band")]
#[case("Rubicon Pluck")]
#[case("Rumble Roll")]
#[case("Rustic")]
#[case("Rustic Wind")]
#[case("Sagittarius X")]
#[case("Sand Steps")]
#[case("Saw Ocean")]
#[case("Saw Star")]
#[case("Schrully")]
#[case("Score Mecha")]
#[case("Scoring Noir")]
#[case("Scrape Scape")]
#[case("Scream Snare")]
#[case("Screamer")]
#[case("Seismic Freq")]
#[case("Sentient Mainframe")]
#[case("Seven Comb")]
#[case("Sgt Stepper")]
#[case("Shakulator")]
#[case("Shifter Spaces")]
#[case("Shivers")]
#[case("Shower Knife")]
#[case("Sid Arp")]
#[case("Silky Road")]
#[case("Sine Cloud")]
#[case("Sine Of The Times")]
#[case("Sine Riders")]
#[case("Siney")]
#[case("Skoop")]
#[case("Sky Hands")]
#[case("Skyscraper")]
#[case("Slap Square")]
#[case("Sleep Paralysis")]
#[case("Slim Jim")]
#[case("Slimey Hoover")]
#[case("Smash Piano")]
#[case("Smashed Circuit")]
#[case("Smooth Flute")]
#[case("Snap Bass")]
#[case("Snap You")]
#[case("Snooze")]
#[case("Soft Gold")]
#[case("Solid Impact")]
#[case("Solid Punch")]
#[case("Sonar Pling")]
#[case("Sonic Breakfast")]
#[case("Soup Noodle")]
#[case("Space Craft")]
#[case("Space Domestic")]
#[case("Space Forest")]
#[case("Space Matter")]
#[case("Space State")]
#[case("Space Thump")]
#[case("Spaced")]
#[case("Spiked")]
#[case("Spiral Lead")]
#[case("Spizz")]
#[case("Splitting Atoms")]
#[case("Spoiled")]
#[case("Spooky Action")]
fn test_parse_preset(#[case] preset_name: &str) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/massive_x_factory_library_tests/fixture")
        .join(format!("{}.nksf", preset_name));

    let nksf = parse_nksf(&path).expect("Failed to parse preset");

    // 全データをYAMLスナップショットとして検証
    insta::assert_yaml_snapshot!(preset_name, nksf);
}
