// プリセット統合テスト Part 1/8
// 自動生成：generators/generate_split_fixture_tests.rs

use nksf_parser::parse_nksf;
use rstest::rstest;
use std::path::PathBuf;

#[rstest]
#[case("Abandoned")]
#[case("Acid Lazers")]
#[case("Advanced Optics")]
#[case("Advancer")]
#[case("Aerial Lift")]
#[case("Aldente Hollywood")]
#[case("Alien Contact")]
#[case("Alkaline State")]
#[case("All Future")]
#[case("All Luck")]
#[case("All Reverse")]
#[case("All Rise")]
#[case("Almost Throat")]
#[case("Alpha Ape")]
#[case("Alpine Digital")]
#[case("Altered States")]
#[case("Alternate Tone")]
#[case("Altitude Crank")]
#[case("Amber Chapel")]
#[case("Ambient Repeats")]
#[case("Ample Wob")]
#[case("Analog Tapestry")]
#[case("Analogica")]
#[case("Anaphylaxis")]
#[case("Anchor Minor")]
#[case("Ancient Future")]
#[case("Ancient Strings")]
#[case("Andean Air")]
#[case("Android")]
#[case("Angelic Sprites")]
#[case("Another Yay")]
#[case("Antelope Springs")]
#[case("Antenna")]
#[case("Anterior Resonance")]
#[case("Anti Eight")]
#[case("Anxious Flutter")]
#[case("Apex Muzzle")]
#[case("Apocalypse Forever")]
#[case("Apricot Pop")]
#[case("April Dawn")]
#[case("Archangel")]
#[case("Arctic Abyss")]
#[case("Arctic Sines")]
#[case("Arena Hands")]
#[case("Art Dual")]
#[case("Artocaster")]
#[case("Asap")]
#[case("Astra Space")]
#[case("Atmosphere Exoplanet")]
#[case("Attack Lazer")]
#[case("Aurora Flutes")]
#[case("Auto Chord")]
#[case("Avenue Bridge")]
#[case("Axe Laugh")]
#[case("Axiom Metal")]
#[case("Balafonic")]
#[case("Balearic Saw")]
#[case("Ballers Ivory")]
#[case("Ballet Mansion")]
#[case("Balloon Time")]
#[case("Bango")]
#[case("Barely Dead")]
#[case("Baritone Strange")]
#[case("Basement Dial Pad")]
#[case("Bass Bandit")]
#[case("Bass Tom")]
#[case("Bassic")]
#[case("Bassoon X")]
#[case("Beach Walker")]
#[case("Beautiful")]
#[case("Becker")]
#[case("Beefy")]
#[case("Beep Layer")]
#[case("Behind You")]
#[case("Bellody")]
#[case("Bellows ")]
#[case("Belly Stage")]
#[case("Beta Breath")]
#[case("Big Cheeks")]
#[case("Big Chip")]
#[case("Bird Box")]
#[case("Birdy Hats")]
#[case("Birdy Swell")]
#[case("Blinded")]
#[case("Blip Drop")]
#[case("Blob Stop")]
#[case("Blueberry")]
#[case("Body Spin")]
#[case("Bohrium")]
#[case("Bongo Bells")]
#[case("Boom Drop")]
#[case("Botox")]
#[case("Bottom Bump")]
#[case("Bow Squad")]
#[case("Bracket")]
#[case("Brain Worm")]
#[case("Brass Stomp")]
#[case("Break Up")]
#[case("Breaker")]
#[case("Bright Superstrings")]
fn test_parse_preset(#[case] preset_name: &str) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/massive_x_factory_library_tests/fixture")
        .join(format!("{}.nksf", preset_name));

    let nksf = parse_nksf(&path).expect("Failed to parse preset");

    // 全データをYAMLスナップショットとして検証
    insta::assert_yaml_snapshot!(preset_name, nksf);
}
