// プリセット統合テスト Part 3/8
// 自動生成：generators/generate_split_fixture_tests.rs

use nksf_parser::parse_nksf;
use rstest::rstest;
use std::path::PathBuf;

#[rstest]
#[case("Dust Bag")]
#[case("Dutch Force")]
#[case("Dynamic Drone")]
#[case("Earthly")]
#[case("Easy Pulse")]
#[case("Eco World")]
#[case("Eddy Hoover")]
#[case("Eight Bells")]
#[case("Eight Rider")]
#[case("Eighties Essential")]
#[case("Eighties Ping")]
#[case("Electra Fizzle")]
#[case("Electric Flow")]
#[case("Electro Alchemist")]
#[case("Elektro Belcher")]
#[case("Elizabeth")]
#[case("Elmo")]
#[case("Embers")]
#[case("Emotion Motion")]
#[case("Emotions Tribute")]
#[case("Empyrean")]
#[case("Ends Way")]
#[case("Ensemble Choir")]
#[case("Epica")]
#[case("Essential Eight")]
#[case("Essex Shuffla")]
#[case("Eternal")]
#[case("Euphoria")]
#[case("Euro Beat")]
#[case("Exalt")]
#[case("Expensive Tastes")]
#[case("Explosive")]
#[case("Extinction Now")]
#[case("Face Down")]
#[case("Face The Punch")]
#[case("Face Warp")]
#[case("Fairy Free")]
#[case("Fallen Crush")]
#[case("Falling Down")]
#[case("Fancy")]
#[case("Faux Arp")]
#[case("Fefi")]
#[case("Festival Island")]
#[case("Filter Ride")]
#[case("Fist Front")]
#[case("Flash Attack")]
#[case("Fluctuation")]
#[case("Fly Fox")]
#[case("Forest Metal")]
#[case("Forever Love")]
#[case("Forever Now")]
#[case("Foundation Focus")]
#[case("Free Solo")]
#[case("Fried Bump")]
#[case("Frog Drop")]
#[case("Fruit Walk")]
#[case("Fuego Synth")]
#[case("Full Blown")]
#[case("Full Speed")]
#[case("Funk Glider")]
#[case("Funk One")]
#[case("Future Hoover")]
#[case("Future Switch")]
#[case("Fuzz Action")]
#[case("Fyre")]
#[case("Galactica")]
#[case("Galaxy Quest")]
#[case("Game Computer")]
#[case("Gamers Glitch")]
#[case("Garage Bonk")]
#[case("Gate System")]
#[case("Gee Six")]
#[case("Ghost Boys")]
#[case("Ghost Shadow")]
#[case("Ghost Whoosh")]
#[case("Glitch Line")]
#[case("Glitch Phantom")]
#[case("Glock Strike")]
#[case("Godzilla Tube")]
#[case("Golden Age")]
#[case("Golden Black")]
#[case("Good Winter")]
#[case("Gooey")]
#[case("Goon Walk")]
#[case("Goonetics")]
#[case("Gorgeous Saws")]
#[case("Gorli Circle")]
#[case("Granny")]
#[case("Green Pastures")]
#[case("Grime Knife")]
#[case("Grind Dragon")]
#[case("Groove Concept")]
#[case("Group Hug")]
#[case("Growler Wob")]
#[case("Hackboard")]
#[case("Hal")]
#[case("Hang Ten")]
#[case("Hangry Gabo")]
#[case("Happy Deejay")]
#[case("Happy Glide")]
fn test_parse_preset(#[case] preset_name: &str) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/massive_x_factory_library_tests/fixture")
        .join(format!("{}.nksf", preset_name));

    let nksf = parse_nksf(&path).expect("Failed to parse preset");

    // 全データをYAMLスナップショットとして検証
    insta::assert_yaml_snapshot!(preset_name, nksf);
}
