// 全720プリセットの統合テスト（rstest + insta）
// 自動生成：tests/generate_unified_fixture_test.rs

use nksf_parser::parse_nksf;
use rstest::rstest;
use std::path::PathBuf;

#[rstest]
#[case("Abandoned")]
#[case("Acid Lazers")]
#[case("Advanced Optics")]
#[case("Advancer")]
#[case("Aerial Lift")]
#[case("Aldente Hollywood")]
#[case("Alien Contact")]
#[case("Alkaline State")]
#[case("All Future")]
#[case("All Luck")]
#[case("All Reverse")]
#[case("All Rise")]
#[case("Almost Throat")]
#[case("Alpha Ape")]
#[case("Alpine Digital")]
#[case("Altered States")]
#[case("Alternate Tone")]
#[case("Altitude Crank")]
#[case("Amber Chapel")]
#[case("Ambient Repeats")]
#[case("Ample Wob")]
#[case("Analog Tapestry")]
#[case("Analogica")]
#[case("Anaphylaxis")]
#[case("Anchor Minor")]
#[case("Ancient Future")]
#[case("Ancient Strings")]
#[case("Andean Air")]
#[case("Android")]
#[case("Angelic Sprites")]
#[case("Another Yay")]
#[case("Antelope Springs")]
#[case("Antenna")]
#[case("Anterior Resonance")]
#[case("Anti Eight")]
#[case("Anxious Flutter")]
#[case("Apex Muzzle")]
#[case("Apocalypse Forever")]
#[case("Apricot Pop")]
#[case("April Dawn")]
#[case("Archangel")]
#[case("Arctic Abyss")]
#[case("Arctic Sines")]
#[case("Arena Hands")]
#[case("Art Dual")]
#[case("Artocaster")]
#[case("Asap")]
#[case("Astra Space")]
#[case("Atmosphere Exoplanet")]
#[case("Attack Lazer")]
#[case("Aurora Flutes")]
#[case("Auto Chord")]
#[case("Avenue Bridge")]
#[case("Axe Laugh")]
#[case("Axiom Metal")]
#[case("Balafonic")]
#[case("Balearic Saw")]
#[case("Ballers Ivory")]
#[case("Ballet Mansion")]
#[case("Balloon Time")]
#[case("Bango")]
#[case("Barely Dead")]
#[case("Baritone Strange")]
#[case("Basement Dial Pad")]
#[case("Bass Bandit")]
#[case("Bass Tom")]
#[case("Bassic")]
#[case("Bassoon X")]
#[case("Beach Walker")]
#[case("Beautiful")]
#[case("Becker")]
#[case("Beefy")]
#[case("Beep Layer")]
#[case("Behind You")]
#[case("Bellody")]
#[case("Bellows ")]
#[case("Belly Stage")]
#[case("Beta Breath")]
#[case("Big Cheeks")]
#[case("Big Chip")]
#[case("Bird Box")]
#[case("Birdy Hats")]
#[case("Birdy Swell")]
#[case("Blinded")]
#[case("Blip Drop")]
#[case("Blob Stop")]
#[case("Blueberry")]
#[case("Body Spin")]
#[case("Bohrium")]
#[case("Bongo Bells")]
#[case("Boom Drop")]
#[case("Botox")]
#[case("Bottom Bump")]
#[case("Bow Squad")]
#[case("Bracket")]
#[case("Brain Worm")]
#[case("Brass Stomp")]
#[case("Break Up")]
#[case("Breaker")]
#[case("Bright Superstrings")]
#[case("Broken Arrow")]
#[case("Broken Bow")]
#[case("Broken Silver")]
#[case("Bubble Inertia")]
#[case("Budgie Bot")]
#[case("Bump Force")]
#[case("Buried Giant")]
#[case("Burn Da Speaker")]
#[case("Burning Psykoma")]
#[case("Burnt Biscuit")]
#[case("Butterherz")]
#[case("Calm Rocket")]
#[case("Canary")]
#[case("Caps Lock")]
#[case("Castle Ancient")]
#[case("Cathedral")]
#[case("Cathedralium")]
#[case("Celestial Plum")]
#[case("Cellar Blip")]
#[case("Cellar Electric")]
#[case("Cesium")]
#[case("Chalice")]
#[case("Chasing Saws")]
#[case("Chicago Galactic")]
#[case("Chord Xfade")]
#[case("Cielo")]
#[case("Circuit Celesta")]
#[case("Circuit Disrupt")]
#[case("City Jazz")]
#[case("Clap Master")]
#[case("Clapped")]
#[case("Clarity")]
#[case("Claws")]
#[case("Clean Strings")]
#[case("Click Fiend")]
#[case("Cloaked")]
#[case("Clock Face")]
#[case("Cloud Air")]
#[case("Cloud Breaker")]
#[case("Clown Play")]
#[case("Club Tropics")]
#[case("Codeword")]
#[case("Coldest Champion")]
#[case("Comb Experiment")]
#[case("Comb Mallets")]
#[case("Come Together")]
#[case("Constant Value")]
#[case("Corellator")]
#[case("Corn Pop")]
#[case("Counting Comets")]
#[case("Cowboy Sync")]
#[case("Cramp")]
#[case("Crash Party")]
#[case("Crayon")]
#[case("Creak Bark")]
#[case("Creature Space")]
#[case("Crispy Lamb")]
#[case("Croco")]
#[case("Crown Alloy")]
#[case("Cruella")]
#[case("Crush Star")]
#[case("Crystal Cactus")]
#[case("Cute Bar")]
#[case("D Arcelious")]
#[case("Daft")]
#[case("Dark Heart")]
#[case("Data Transmissions")]
#[case("Daybreaker")]
#[case("Dazed Strange")]
#[case("Deception")]
#[case("Deep Blue")]
#[case("Deep Float")]
#[case("Deep Forward")]
#[case("Deep Fried")]
#[case("Deep Growl")]
#[case("Department Box")]
#[case("Desist")]
#[case("Destination Source")]
#[case("Destroyer")]
#[case("Devine Acid")]
#[case("Diesel Dust")]
#[case("Digital Ghost")]
#[case("Dirty Dancer")]
#[case("Dodo Scream")]
#[case("Dolphin")]
#[case("Dopamine Pluck")]
#[case("Down Down")]
#[case("Dream Away")]
#[case("Dreamy Amazonia")]
#[case("Drift Away")]
#[case("Drifter")]
#[case("Dripping Space")]
#[case("Drop Conga")]
#[case("Drop Lazer")]
#[case("Dub Bounce")]
#[case("Dub Salad")]
#[case("Dub Spiral")]
#[case("Dub Stick")]
#[case("Dunkin Bass")]
#[case("Dunkle")]
#[case("Dust Bag")]
#[case("Dutch Force")]
#[case("Dynamic Drone")]
#[case("Earthly")]
#[case("Easy Pulse")]
#[case("Eco World")]
#[case("Eddy Hoover")]
#[case("Eight Bells")]
#[case("Eight Rider")]
#[case("Eighties Essential")]
#[case("Eighties Ping")]
#[case("Electra Fizzle")]
#[case("Electric Flow")]
#[case("Electro Alchemist")]
#[case("Elektro Belcher")]
#[case("Elizabeth")]
#[case("Elmo")]
#[case("Embers")]
#[case("Emotion Motion")]
#[case("Emotions Tribute")]
#[case("Empyrean")]
#[case("Ends Way")]
#[case("Ensemble Choir")]
#[case("Epica")]
#[case("Essential Eight")]
#[case("Essex Shuffla")]
#[case("Eternal")]
#[case("Euphoria")]
#[case("Euro Beat")]
#[case("Exalt")]
#[case("Expensive Tastes")]
#[case("Explosive")]
#[case("Extinction Now")]
#[case("Face Down")]
#[case("Face The Punch")]
#[case("Face Warp")]
#[case("Fairy Free")]
#[case("Fallen Crush")]
#[case("Falling Down")]
#[case("Fancy")]
#[case("Faux Arp")]
#[case("Fefi")]
#[case("Festival Island")]
#[case("Filter Ride")]
#[case("Fist Front")]
#[case("Flash Attack")]
#[case("Fluctuation")]
#[case("Fly Fox")]
#[case("Forest Metal")]
#[case("Forever Love")]
#[case("Forever Now")]
#[case("Foundation Focus")]
#[case("Free Solo")]
#[case("Fried Bump")]
#[case("Frog Drop")]
#[case("Fruit Walk")]
#[case("Fuego Synth")]
#[case("Full Blown")]
#[case("Full Speed")]
#[case("Funk Glider")]
#[case("Funk One")]
#[case("Future Hoover")]
#[case("Future Switch")]
#[case("Fuzz Action")]
#[case("Fyre")]
#[case("Galactica")]
#[case("Galaxy Quest")]
#[case("Game Computer")]
#[case("Gamers Glitch")]
#[case("Garage Bonk")]
#[case("Gate System")]
#[case("Gee Six")]
#[case("Ghost Boys")]
#[case("Ghost Shadow")]
#[case("Ghost Whoosh")]
#[case("Glitch Line")]
#[case("Glitch Phantom")]
#[case("Glock Strike")]
#[case("Godzilla Tube")]
#[case("Golden Age")]
#[case("Golden Black")]
#[case("Good Winter")]
#[case("Gooey")]
#[case("Goon Walk")]
#[case("Goonetics")]
#[case("Gorgeous Saws")]
#[case("Gorli Circle")]
#[case("Granny")]
#[case("Green Pastures")]
#[case("Grime Knife")]
#[case("Grind Dragon")]
#[case("Groove Concept")]
#[case("Group Hug")]
#[case("Growler Wob")]
#[case("Hackboard")]
#[case("Hal")]
#[case("Hang Ten")]
#[case("Hangry Gabo")]
#[case("Happy Deejay")]
#[case("Happy Glide")]
#[case("Happy Sawtooths")]
#[case("Hard Bass")]
#[case("Hard Hats")]
#[case("Hard Nine")]
#[case("Harmonication")]
#[case("Harvest")]
#[case("Haunted House")]
#[case("Helios Punch")]
#[case("Hidden Monster")]
#[case("Higher Hats")]
#[case("Hip")]
#[case("Hold Beat")]
#[case("Hollow Talk")]
#[case("Hollowgrafic")]
#[case("Honey Stack")]
#[case("Hoover")]
#[case("Horn Score")]
#[case("Horn Stab")]
#[case("House Strings")]
#[case("Hunting Game")]
#[case("Hyper Line")]
#[case("Hypnoteck")]
#[case("Iced Keys")]
#[case("Inner Nature")]
#[case("Inorganic")]
#[case("Insane Membrane")]
#[case("Into Abyss")]
#[case("Iron Ivory")]
#[case("Iron Throne")]
#[case("Irregular Pong")]
#[case("Island Life")]
#[case("Island Pluck")]
#[case("Islands")]
#[case("Jackal")]
#[case("Jazz Man")]
#[case("Jazzerism")]
#[case("Joker Break")]
#[case("Jump Chord")]
#[case("Junox Poly")]
#[case("Just Rain")]
#[case("Kali")]
#[case("Kesselbeat")]
#[case("Kicka")]
#[case("Kiki Cat")]
#[case("Kingson Brown")]
#[case("Klattern")]
#[case("Komplex Line")]
#[case("Kong Donk")]
#[case("Kongao")]
#[case("Lad Time")]
#[case("Landslide")]
#[case("Laser Scream")]
#[case("Laser Splash")]
#[case("Lately")]
#[case("Lazer Dust")]
#[case("Lazy Gun")]
#[case("Legacy X")]
#[case("Lets Dance")]
#[case("Lights On")]
#[case("Liquid Triad")]
#[case("Little Beeper")]
#[case("Lofi Jitter")]
#[case("Log Off")]
#[case("Lola")]
#[case("Lost")]
#[case("Lovely Eighties")]
#[case("Lush Cascade")]
#[case("Lush Dome")]
#[case("Lush Upright")]
#[case("M Tech Pluck")]
#[case("Machine Kick")]
#[case("Mafia Eight")]
#[case("Magic Bells")]
#[case("Magic Man")]
#[case("Magnesium")]
#[case("Major Blade")]
#[case("Mallets Mallet")]
#[case("Mango Pop")]
#[case("Mashed")]
#[case("Massive Impact")]
#[case("Massive Raw")]
#[case("Matrix Metal")]
#[case("Matrix Rainfall")]
#[case("Maximus Brute")]
#[case("Maya")]
#[case("Mech Attack")]
#[case("Mega Up")]
#[case("Megaworm")]
#[case("Melancholic Hoarse")]
#[case("Melancholic Rims")]
#[case("Mellow Organ")]
#[case("Melo Square")]
#[case("Melodic Ground")]
#[case("Metal Bend")]
#[case("Metallic Aura")]
#[case("Midtown Swirl")]
#[case("Mild Sauce")]
#[case("Mini Ark")]
#[case("Minor Hit")]
#[case("Minor Rise")]
#[case("Missile Man")]
#[case("Missing Beats")]
#[case("Modern Eight")]
#[case("Modern Funk")]
#[case("Modern Slap")]
#[case("Moldy Organ")]
#[case("Monark King")]
#[case("Monkey Forest")]
#[case("Moon Ark")]
#[case("Moony")]
#[case("Moregan")]
#[case("Morph Suitcase")]
#[case("Morse Chords")]
#[case("Mother Doom")]
#[case("Motor Braam")]
#[case("Mouth Chilly")]
#[case("Moving Monster")]
#[case("Moving On")]
#[case("Mr Snappy")]
#[case("Multi Phasor")]
#[case("Mumble Growl")]
#[case("Music Auto")]
#[case("Muted Axe")]
#[case("Mystery Metal")]
#[case("Mystic Visions")]
#[case("Naked Saw")]
#[case("Naturalistic")]
#[case("Naughties")]
#[case("Naughty Noise")]
#[case("Negative Matter")]
#[case("Neo Soul")]
#[case("Neon Rain")]
#[case("Neu Metal")]
#[case("Night Trails")]
#[case("No Zone")]
#[case("Noise Bells")]
#[case("Noise Pulse")]
#[case("Noise Sub")]
#[case("Not Scary")]
#[case("Now Dystopia")]
#[case("Obsession")]
#[case("Obstacles")]
#[case("Oceanic Storm")]
#[case("Octave Drums")]
#[case("Octave Loop")]
#[case("Odd World")]
#[case("On Fire")]
#[case("One Note")]
#[case("One Patch to Rule Them All")]
#[case("Opaque Saws")]
#[case("Open Close")]
#[case("Optical Tension")]
#[case("Orbit Mist")]
#[case("Orchestra Bubbles")]
#[case("Orchestral Poly")]
#[case("Organ Gator")]
#[case("Organ House")]
#[case("Organic Closer")]
#[case("Organic Log")]
#[case("Outlaw")]
#[case("Over Rainbow")]
#[case("Oxygen Mask")]
#[case("Palm City")]
#[case("Paloma")]
#[case("Pandora")]
#[case("Paradise")]
#[case("Party Bonk")]
#[case("Passive")]
#[case("Pastoral Landscape")]
#[case("Pathways")]
#[case("Pedal Blades")]
#[case("Peters Pan")]
#[case("Phat Phase")]
#[case("Phazer")]
#[case("Piccolino")]
#[case("Pineapple")]
#[case("Ping Latency")]
#[case("Pink Bleep")]
#[case("Pipe Man")]
#[case("Pixel")]
#[case("Plastique")]
#[case("Plate Bender")]
#[case("Playful")]
#[case("Playing The Amp")]
#[case("Plec Snap")]
#[case("Plop Pluck")]
#[case("Pluck Attack")]
#[case("Plucked Up")]
#[case("Plucky")]
#[case("Plush")]
#[case("Poetic Popcorn")]
#[case("Poly Tech")]
#[case("Port Meadow")]
#[case("Primal Leader")]
#[case("Prog Lead")]
#[case("Psy Drips")]
#[case("Pucker")]
#[case("Puffy Mallet")]
#[case("Pulse Rider")]
#[case("Push Kick")]
#[case("Quack")]
#[case("Quantum Foam")]
#[case("Quantum Hopper")]
#[case("Quartet Time")]
#[case("R2T2")]
#[case("Racer Raver")]
#[case("Radioactive")]
#[case("Rampenschutz")]
#[case("Random Orders")]
#[case("Randomitter")]
#[case("Ratios")]
#[case("Rattle Shake")]
#[case("Rattlesnake")]
#[case("Rave Forest")]
#[case("Raving Beast")]
#[case("Reckoning")]
#[case("Reel Keys")]
#[case("Resolute")]
#[case("Retaliation Is A Must")]
#[case("Retro Cruiser")]
#[case("Retro Dub")]
#[case("Retro Hoover")]
#[case("Retro Rise")]
#[case("Retrograde")]
#[case("Ringer")]
#[case("Rip Tear")]
#[case("Rip Teeth")]
#[case("Riser Collection")]
#[case("Rising Star")]
#[case("Rising Sun")]
#[case("Robot Wars")]
#[case("Robotic Ape")]
#[case("Rock Hats")]
#[case("Rock Register")]
#[case("Roller Shake")]
#[case("Rough Rider")]
#[case("Round Trip")]
#[case("Rub Lamp")]
#[case("Rubber")]
#[case("Rubber Band")]
#[case("Rubicon Pluck")]
#[case("Rumble Roll")]
#[case("Rustic")]
#[case("Rustic Wind")]
#[case("Sagittarius X")]
#[case("Sand Steps")]
#[case("Saw Ocean")]
#[case("Saw Star")]
#[case("Schrully")]
#[case("Score Mecha")]
#[case("Scoring Noir")]
#[case("Scrape Scape")]
#[case("Scream Snare")]
#[case("Screamer")]
#[case("Seismic Freq")]
#[case("Sentient Mainframe")]
#[case("Seven Comb")]
#[case("Sgt Stepper")]
#[case("Shakulator")]
#[case("Shifter Spaces")]
#[case("Shivers")]
#[case("Shower Knife")]
#[case("Sid Arp")]
#[case("Silky Road")]
#[case("Sine Cloud")]
#[case("Sine Of The Times")]
#[case("Sine Riders")]
#[case("Siney")]
#[case("Skoop")]
#[case("Sky Hands")]
#[case("Skyscraper")]
#[case("Slap Square")]
#[case("Sleep Paralysis")]
#[case("Slim Jim")]
#[case("Slimey Hoover")]
#[case("Smash Piano")]
#[case("Smashed Circuit")]
#[case("Smooth Flute")]
#[case("Snap Bass")]
#[case("Snap You")]
#[case("Snooze")]
#[case("Soft Gold")]
#[case("Solid Impact")]
#[case("Solid Punch")]
#[case("Sonar Pling")]
#[case("Sonic Breakfast")]
#[case("Soup Noodle")]
#[case("Space Craft")]
#[case("Space Domestic")]
#[case("Space Forest")]
#[case("Space Matter")]
#[case("Space State")]
#[case("Space Thump")]
#[case("Spaced")]
#[case("Spiked")]
#[case("Spiral Lead")]
#[case("Spizz")]
#[case("Splitting Atoms")]
#[case("Spoiled")]
#[case("Spooky Action")]
#[case("Spring Coils")]
#[case("Springboard")]
#[case("Springy Walk")]
#[case("Sprinkle Pad")]
#[case("Stabbath")]
#[case("Stabbed Chord")]
#[case("Stacked")]
#[case("Star Wash")]
#[case("Station Noise")]
#[case("Steam Pan")]
#[case("Steamy Strike")]
#[case("Stellar Drift")]
#[case("Stock Wire")]
#[case("Stone Wheel")]
#[case("Strange Acid")]
#[case("String Bundle")]
#[case("Struggling Around")]
#[case("Stubby")]
#[case("Stun Wash")]
#[case("Sub Breese")]
#[case("Sub Pop")]
#[case("Subsistence")]
#[case("Subterra")]
#[case("Summer Metal")]
#[case("Sun Rays")]
#[case("Sunken Ship")]
#[case("Sunny Island")]
#[case("Super Corrupt")]
#[case("Super Soaker")]
#[case("Super Swell")]
#[case("Surf Explorer")]
#[case("Swamp Lazer")]
#[case("Sweep Tool")]
#[case("Sweet Heaven")]
#[case("Sweet Tap")]
#[case("Swirl")]
#[case("Switch Bud")]
#[case("Swoosh Swell")]
#[case("TV Memory")]
#[case("Taser Reel")]
#[case("Techa")]
#[case("Techtronic")]
#[case("Terabyte")]
#[case("Texture Patch")]
#[case("The Arpology")]
#[case("The Bells")]
#[case("The Calm")]
#[case("The Competition")]
#[case("The End")]
#[case("The Gathering")]
#[case("The Joker")]
#[case("The Orb")]
#[case("The Performer")]
#[case("The Swarm")]
#[case("Third Aspect")]
#[case("Tight Combo")]
#[case("Timberline")]
#[case("Time Wind")]
#[case("Titanic Eight")]
#[case("To Ashes")]
#[case("Transient")]
#[case("Transient Steel")]
#[case("Transistor Bump")]
#[case("Trap Robber")]
#[case("Treasure")]
#[case("Trickster Stab")]
#[case("Trident")]
#[case("Tripper")]
#[case("Tristesse")]
#[case("Tropical Triad")]
#[case("Tube")]
#[case("Tuby Tuesday")]
#[case("Turbo Boost")]
#[case("Twisted Simple")]
#[case("Two Left Feet")]
#[case("Ukulele Strum")]
#[case("Uncle John")]
#[case("Under Ground")]
#[case("Unduster")]
#[case("Up Growl")]
#[case("Urban Eight")]
#[case("Vantage")]
#[case("Velodrome")]
#[case("Vice")]
#[case("Victim")]
#[case("Victory Call")]
#[case("Vintage Pro")]
#[case("Vivid Voyager")]
#[case("Voice Bot")]
#[case("Voiced Ratio")]
#[case("Voices")]
#[case("Wafty")]
#[case("Warm Float")]
#[case("Water Lights")]
#[case("Water Pipes")]
#[case("Waves")]
#[case("West Hill")]
#[case("Whip It")]
#[case("Whirly Gate")]
#[case("White")]
#[case("Wide Awake")]
#[case("Wild Pitch")]
#[case("Wintery Tinkle")]
#[case("Wipeout")]
#[case("Wisdom Oracle")]
#[case("Wob Repeat")]
#[case("Wob You")]
#[case("Wobbly Orbit")]
#[case("Wonky Comb")]
#[case("Wooden Attack")]
#[case("Wooden Strike")]
#[case("Wooden String")]
#[case("Woozle")]
#[case("World Park")]
#[case("Wowzer")]
#[case("Wub Goo")]
#[case("Xberg Wunder")]
#[case("Zaddy")]
#[case("Zitteraal")]
#[case("Zytrus Silk")]

fn test_parse_preset(#[case] preset_name: &str) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/massive_x_factory_library_tests/fixture")
        .join(format!("{}.nksf", preset_name));

    let nksf = parse_nksf(&path).expect("Failed to parse preset");

    // 全データをYAMLスナップショットとして検証
    insta::assert_yaml_snapshot!(preset_name, nksf);
}
