// プリセット統合テスト Part 7/8
// 自動生成：generators/generate_split_fixture_tests.rs

use nksf_parser::parse_nksf;
use rstest::rstest;
use std::path::PathBuf;

#[rstest]
#[case("Spring Coils")]
#[case("Springboard")]
#[case("Springy Walk")]
#[case("Sprinkle Pad")]
#[case("Stabbath")]
#[case("Stabbed Chord")]
#[case("Stacked")]
#[case("Star Wash")]
#[case("Station Noise")]
#[case("Steam Pan")]
#[case("Steamy Strike")]
#[case("Stellar Drift")]
#[case("Stock Wire")]
#[case("Stone Wheel")]
#[case("Strange Acid")]
#[case("String Bundle")]
#[case("Struggling Around")]
#[case("Stubby")]
#[case("Stun Wash")]
#[case("Sub Breese")]
#[case("Sub Pop")]
#[case("Subsistence")]
#[case("Subterra")]
#[case("Summer Metal")]
#[case("Sun Rays")]
#[case("Sunken Ship")]
#[case("Sunny Island")]
#[case("Super Corrupt")]
#[case("Super Soaker")]
#[case("Super Swell")]
#[case("Surf Explorer")]
#[case("Swamp Lazer")]
#[case("Sweep Tool")]
#[case("Sweet Heaven")]
#[case("Sweet Tap")]
#[case("Swirl")]
#[case("Switch Bud")]
#[case("Swoosh Swell")]
#[case("TV Memory")]
#[case("Taser Reel")]
#[case("Techa")]
#[case("Techtronic")]
#[case("Terabyte")]
#[case("Texture Patch")]
#[case("The Arpology")]
#[case("The Bells")]
#[case("The Calm")]
#[case("The Competition")]
#[case("The End")]
#[case("The Gathering")]
#[case("The Joker")]
#[case("The Orb")]
#[case("The Performer")]
#[case("The Swarm")]
#[case("Third Aspect")]
#[case("Tight Combo")]
#[case("Timberline")]
#[case("Time Wind")]
#[case("Titanic Eight")]
#[case("To Ashes")]
#[case("Transient")]
#[case("Transient Steel")]
#[case("Transistor Bump")]
#[case("Trap Robber")]
#[case("Treasure")]
#[case("Trickster Stab")]
#[case("Trident")]
#[case("Tripper")]
#[case("Tristesse")]
#[case("Tropical Triad")]
#[case("Tube")]
#[case("Tuby Tuesday")]
#[case("Turbo Boost")]
#[case("Twisted Simple")]
#[case("Two Left Feet")]
#[case("Ukulele Strum")]
#[case("Uncle John")]
#[case("Under Ground")]
#[case("Unduster")]
#[case("Up Growl")]
#[case("Urban Eight")]
#[case("Vantage")]
#[case("Velodrome")]
#[case("Vice")]
#[case("Victim")]
#[case("Victory Call")]
#[case("Vintage Pro")]
#[case("Vivid Voyager")]
#[case("Voice Bot")]
#[case("Voiced Ratio")]
#[case("Voices")]
#[case("Wafty")]
#[case("Warm Float")]
#[case("Water Lights")]
#[case("Water Pipes")]
#[case("Waves")]
#[case("West Hill")]
#[case("Whip It")]
#[case("Whirly Gate")]
#[case("White")]
fn test_parse_preset(#[case] preset_name: &str) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/massive_x_factory_library_tests/fixture")
        .join(format!("{}.nksf", preset_name));

    let nksf = parse_nksf(&path).expect("Failed to parse preset");

    // 全データをYAMLスナップショットとして検証
    insta::assert_yaml_snapshot!(preset_name, nksf);
}
