// プリセット統合テスト Part 4/8
// 自動生成：generators/generate_split_fixture_tests.rs

use nksf_parser::parse_nksf;
use rstest::rstest;
use std::path::PathBuf;

#[rstest]
#[case("Happy Sawtooths")]
#[case("Hard Bass")]
#[case("Hard Hats")]
#[case("Hard Nine")]
#[case("Harmonication")]
#[case("Harvest")]
#[case("Haunted House")]
#[case("Helios Punch")]
#[case("Hidden Monster")]
#[case("Higher Hats")]
#[case("Hip")]
#[case("Hold Beat")]
#[case("Hollow Talk")]
#[case("Hollowgrafic")]
#[case("Honey Stack")]
#[case("Hoover")]
#[case("Horn Score")]
#[case("Horn Stab")]
#[case("House Strings")]
#[case("Hunting Game")]
#[case("Hyper Line")]
#[case("Hypnoteck")]
#[case("Iced Keys")]
#[case("Inner Nature")]
#[case("Inorganic")]
#[case("Insane Membrane")]
#[case("Into Abyss")]
#[case("Iron Ivory")]
#[case("Iron Throne")]
#[case("Irregular Pong")]
#[case("Island Life")]
#[case("Island Pluck")]
#[case("Islands")]
#[case("Jackal")]
#[case("Jazz Man")]
#[case("Jazzerism")]
#[case("Joker Break")]
#[case("Jump Chord")]
#[case("Junox Poly")]
#[case("Just Rain")]
#[case("Kali")]
#[case("Kesselbeat")]
#[case("Kicka")]
#[case("Kiki Cat")]
#[case("Kingson Brown")]
#[case("Klattern")]
#[case("Komplex Line")]
#[case("Kong Donk")]
#[case("Kongao")]
#[case("Lad Time")]
#[case("Landslide")]
#[case("Laser Scream")]
#[case("Laser Splash")]
#[case("Lately")]
#[case("Lazer Dust")]
#[case("Lazy Gun")]
#[case("Legacy X")]
#[case("Lets Dance")]
#[case("Lights On")]
#[case("Liquid Triad")]
#[case("Little Beeper")]
#[case("Lofi Jitter")]
#[case("Log Off")]
#[case("Lola")]
#[case("Lost")]
#[case("Lovely Eighties")]
#[case("Lush Cascade")]
#[case("Lush Dome")]
#[case("Lush Upright")]
#[case("M Tech Pluck")]
#[case("Machine Kick")]
#[case("Mafia Eight")]
#[case("Magic Bells")]
#[case("Magic Man")]
#[case("Magnesium")]
#[case("Major Blade")]
#[case("Mallets Mallet")]
#[case("Mango Pop")]
#[case("Mashed")]
#[case("Massive Impact")]
#[case("Massive Raw")]
#[case("Matrix Metal")]
#[case("Matrix Rainfall")]
#[case("Maximus Brute")]
#[case("Maya")]
#[case("Mech Attack")]
#[case("Mega Up")]
#[case("Megaworm")]
#[case("Melancholic Hoarse")]
#[case("Melancholic Rims")]
#[case("Mellow Organ")]
#[case("Melo Square")]
#[case("Melodic Ground")]
#[case("Metal Bend")]
#[case("Metallic Aura")]
#[case("Midtown Swirl")]
#[case("Mild Sauce")]
#[case("Mini Ark")]
#[case("Minor Hit")]
#[case("Minor Rise")]
fn test_parse_preset(#[case] preset_name: &str) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/massive_x_factory_library_tests/fixture")
        .join(format!("{}.nksf", preset_name));

    let nksf = parse_nksf(&path).expect("Failed to parse preset");

    // 全データをYAMLスナップショットとして検証
    insta::assert_yaml_snapshot!(preset_name, nksf);
}
