name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      
      - name: Check code formatting
        run: cargo fmt --all -- --check
      - name: Run Clippy
        run: cargo clippy
      - name: Download and validate test fixtures
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_ENDPOINT_URL_S3: ${{ secrets.R2_ENDPOINT }}
        run: |
          # Download archive
          aws s3 cp s3://nksf-parser-fixtures/massive_x_factory_library_tests_fixtures.7z /tmp
          echo c4c0e2d5aecdb7a8d27bb6864e52bf87a06021f74bfcaa870654ba567fd3fe63  /tmp/massive_x_factory_library_tests_fixtures.7z | sha256sum -c

          # Extract archive
          (
            cd lib/tests
            7z x -omassive_x_factory_library_tests/fixture /tmp/massive_x_factory_library_tests_fixtures.7z
            sha256sum -c checksum.sha256 --quiet
          )

          # Remove archive
          rm /tmp/massive_x_factory_library_tests_fixtures.7z

      - name: Run tests
        run: |
          cargo nextest run

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            filename: nksf-parser-cli
          - target: aarch64-unknown-linux-gnu
            depends: crossbuild-essential-arm64
            filename: nksf-parser-cli
          - target: x86_64-pc-windows-gnu
            depends: mingw-w64
            filename: nksf-parser-cli.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup rust environment
        run: rustup target add "${{ matrix.target }}"

      - name: Install dependencies (${{ matrix.target }})
        if: ${{ matrix.depends != '' }}
        run: |
          sudo apt update
          sudo apt install -y ${{ matrix.depends }}

      - name: Build CLI
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        run: |
          cargo build -p nksf-parser-cli --release --target "${{ matrix.target }}"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: nksf-parser-cli-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.filename }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Download all build artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts
      - name: Rename files
        run: |
          mkdir -p artifacts/files
          for file in $(ls artifacts/**/*)
          do
            RENAMED="$(echo $file | sed -E 's/^(artifacts\/)(.+)\/[^\.]+(\.?.*)$/\1files\/\2\3/')"
            echo -e "$file\t->\t$RENAMED"
            mv "$file" "$RENAMED"
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true
          files: ./artifacts/files/*
